# Use root/example as user/password credentials
version: '3.7'
services:
  mongodb:
    image: mongo:latest
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - streamlit-webapp-network
  streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    volumes:
      - './:/usr/src/app/'
    depends_on:
      - mongodb
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: password
      MONGO_DB_HOSTNAME: mongodb
    networks:
      - streamlit-webapp-network

networks:
  streamlit-webapp-network:
    driver: bridge

volumes:
  mongodb_data_container:

